name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type DESTROY to confirm"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  destroy-plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Validate Confirmation
        run: |
          if [ "${{ github.event.inputs.confirm_destroy }}" != "DESTROY" ]; then
            echo "Please type DESTROY to continue."
            exit 1
          fi

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy Plan
        run: terraform plan -destroy -out=destroy.tfplan

      - name: Upload Destroy Plan
        uses: actions/upload-artifact@v4
        with:
          name: destroy-plan
          path: terraform/destroy.tfplan

  destroy:
    needs: destroy-plan
    runs-on: ubuntu-latest

    # GitHub pauses here until the deployment is approved
    environment:
      name: dev

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Download Destroy Plan
        uses: actions/download-artifact@v4
        with:
          name: destroy-plan
          path: terraform

      - name: Apply Destroy Plan
        run: terraform apply -input=false destroy.tfplan